### PR TITLE
Update Vagrantfile and Vagrant Documentation

### PR DESCRIPTION
**Pull request by ddubau**
Updated Vagrantfile to use private network, ssh forwarding and nat. Also change aptitude to update first in provisioning.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Great stuff! Is there anyway to hook the plugins up to the Vagrant config file (to make them install automatically) ?

**Comment by ddubau** [comment]
There is no way to automatically install vagrant plugins that I know of.

**Comment by andersevenrud** [comment]
Allright :)

**Comment by andersevenrud** [comment]
Is there a way to set up a "repository" like with Docker ? So you don't have to use the Vagrantfile, but an URL ?

**Pull request merged**
