### PR TITLE
[Locale] Turkish (tr_TR) translations

### PR DESCRIPTION
**Pull request by yasintoy**

### CODE REVIEW

**Comment by andersevenrud** [comment]
Thank you very much! :)

Can you also take care of the Application translations ?

**Comment by yasintoy** [comment]
Of course and also I missed some "",'' etc and I'm trying to fix.How can I translate application?

**Comment by andersevenrud** [comment]
You can look here for instructions on that: https://github.com/andersevenrud/OS.js-v2/wiki/Join-the-translation-team#application-instructions

**Comment by yasintoy** [comment]
As soon as I'll start :)

**Comment by andersevenrud** [comment]
:+1:

**Comment by yasintoy** [comment]
merry christmas

**Comment by andersevenrud** [comment]
and a happy new year! :)

**Comment by yasintoy** [comment]
I finished to translate.Now,How can I help without translation? I really want to more help

**Comment by andersevenrud** [comment]
@yasintoy Well, what would you like to do ? :)

**Comment by andersevenrud** [comment]
You can also check for any missing strings and fill in those (See if there are still english words)

**Comment by yasintoy** [comment]
I know,there are still english words(maybe 10 words) but translataion of some english words was so difficult.Now, I'm researching their means and as soon as I'll translate. On the other hand ,I know Python,html,css and a little bit javascript(nowadays,I'm learning more),may i be of some assistance to you,if it's possible

**Pull request merged**
