### PR TITLE
Locales: Adding new pt_BR (Brazilian Portuguese) to Locales

### PR DESCRIPTION
**Pull request by filipeforattini**
*Hello Anders!* I must say that loved your project and I see so much potential! The architecture is very nice and clean, seriously, good job!

I humbly bring a translation into Brazilian Portuguese **pt_BR** your project's core, and soon I'll also bring the applications' translations, ok?

Obs: There are some phrases to be reviewed (maybe by another portuguese speaker) for better understanding with the words *'application'*, *'applications'* and *'programs'*, mainly because we have changed over there years how to use those words in Brazil; sometimes being used as *"programs"*, others like *"apps"* or *"applications"*. Well, I guess it happened over the whole world, but yeah, to be reviewed.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Hi Fillipe :)

Thank you for the kind words! It's nice to get feedback on the code and architecture (as very few has done this).

It seems that you have some conflicts in the pull-request, so I cannot merge it. Is your repository up-to-date ?

**Comment by filipeforattini** [comment]
Sorry, It was terribly outdated...

**Comment by filipeforattini** [comment]
On **.travis.yml**, working with mocha locally (without the --global) made Grunt find the module. Is *it* a requirement?

**Comment by andersevenrud** [comment]
mocha is not a requirement. It is just for running the server-side tests (I'm not sure I understood you correctly)

**Comment by filipeforattini** [comment]
I'm talking about this check from Travis CI that didnt find the Mocha module. So I ran *npm test* here and didnt work, after I changed **.travis.yml** and took off the "-g" from mocha; it found the module locally.

Unfortunately i'm running this repository on windows and my git had autocrlf set to true; grunt is *sensitive* to that. :(

**Comment by andersevenrud** [comment]
It runs just fine on master branch.

If you take a close look at this pull-request, something is not right.

It says 20 files changed (including removals that should not be there). Some file permissions also seem to have changed.

Mocha installation is unrelated. Look at this:
> >> Error: Cannot find module '/home/travis/build/andersevenrud/OS.js-v2/src/server/node/node_modules/osjs/osjs.js'

Mocha fails because it cannot find this file. Your pull request removed it!

**Comment by filipeforattini** [comment]
Ok, gonna copy the translation file and make another pull request with newest version of your code.

**Pull request closed without merging**
