### PR TITLE
'Other' renamed

### PR DESCRIPTION
**Pull request by MrSchism**
Reclassified 'Unknown' apps to 'Other' apps.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Lol... I just realized where this guy saw "Other".... it's in the friggin' locale file of CoreWM.

So this will work without requesting changes from the locale maintainers :smile:

**Comment by andersevenrud** [comment]
Oh. And, thanks, mate :)

**Comment by MrSchism** [comment]
No worries.  Looking over it, if I didn't change that, I'd have had to change the name of the icon and references to it elsewhere because the icon itself was referred to as `applications-other.png`

**Comment by andersevenrud** [comment]
Ops. Actually did not check this closly enought. Look  at this https://github.com/andersevenrud/OS.js-v2/commit/b742cf6d4b8766457e4f75883d7ccb9a1819f77c

Only changing the label is required. If you do not select a category in the package it will automatically set it to "unknown" (the key)

**Comment by andersevenrud** [comment]
Locale is already in place. Ex: https://github.com/andersevenrud/OS.js-v2/blob/master/src/packages/default/CoreWM/locales.js#L55

**Comment by andersevenrud** [comment]
Sorry for spamming your inbox. To clarify: 

If the package category is not one of these: development, education, games, graphics, network, multimedia, office, system, utilities ; it will automatically assume it's "unknown" therefore changing the key is not required, only the label (if that made it any clearer) :)

**Comment by MrSchism** [comment]
With the emails I get from [ValveSoftware](https://github.com/ValveSoftware), [i3](https://github.com/i3/i3), and [PhotonStorm](https://github.com/photonstorm/phaser), it's impossible to call this stuff 'spam'.

I saw what you changed after and realized where I screwed up; thanks for catching that.

**Pull request merged**
