### PR TITLE
add spanish locale

### PR DESCRIPTION
**Pull request by sieira**
Well... just a Spanish (from Spain) Spanish translation. I should be good for any Spanish variant, 'though

### CODE REVIEW

**Comment by andersevenrud** [comment]
Great stuff! Could you possibly translate the other components of OS.js ? :)

**Comment by sieira** [comment]
Sure ! I just have to find the files :-p

**Comment by andersevenrud** [comment]
+1

I have a wiki page for exactly this: https://github.com/andersevenrud/OS.js-v2/wiki/Join-the-translation-team

Also and issue if you want to discuss the topic: https://github.com/andersevenrud/OS.js-v2/issues/18

**Comment by andersevenrud** [comment]
I will probably leave this pull-request open in case more changes comes in :)

**Comment by sieira** [comment]
Well, that's all for today

**Comment by sieira** [comment]
Done

**Comment by andersevenrud** [comment]
Looks good. I'll merge this now since it has the most important stuff in place.

Thanks a million!

**Comment by andersevenrud** [comment]
https://github.com/andersevenrud/OS.js-v2/wiki/Hall-of-Fame

**Pull request merged**
