### PR TITLE
Update vi_VN locales and add some functions in Right-click Menu

### PR DESCRIPTION
**Pull request by khoaakt**

### CODE REVIEW

**Comment by ComputeLinux** [comment]
me wanty

**Comment by khoaakt** [comment]
@ComputeLinux eh?

**Comment by andersevenrud** [comment]
I'll merge this tomorrow

**Comment by andersevenrud** [comment]
This was merged. No idea why github did not update.

Please study the changes I made:

- https://github.com/andersevenrud/OS.js-v2/blob/master/src/packages/default/CoreWM/panel.js#L61
- https://github.com/andersevenrud/OS.js-v2/blob/master/src/packages/default/CoreWM/main.js#L842

I reduced your code by ~50% :)

**Comment by andersevenrud** [comment]
Is your forked repository deleted or private ?

**Comment by khoaakt** [comment]
@andersevenrud I missed :disappointed: , deleted it.

**Comment by andersevenrud** [comment]
Oh. That was why I had some problems them. Why ? :P

**Comment by khoaakt** [comment]
I update it to ng-ui :)

**Pull request closed without merging**
