### PR TITLE
Start OS.js node Windows

### PR DESCRIPTION
**Pull request by staticextasy**
BATCH CMD file to start node's server for OS.js

### CODE REVIEW

**Comment by andersevenrud** [comment]
I was actually thinking about including some launchers and shortcuts, but have them stored in a folder called "bin/" in the root.

I don't like having lots of files in the root because it makes the project look messy and unorganized.

So if you could create this directory and move it into there, that'd be great. Also I feel that using lowercase letters for filenames is best practice.

Tip: You don't need to create a new pull  request every time you make a change in the same branch. This will automatically update with your latest commits (I think) :)

**Comment by staticextasy** [comment]
Made the changes, the capitalization is habit from programming haha. You're right it did auto-update the changes.

**Comment by andersevenrud** [comment]
FYI: Changed it to "win-start-node-dist.cmd". Added some more launchers for all platforms into bin/ :)

**Comment by khoaakt** [comment]
Or something like this :smile: 
zzz

**Pull request merged**
