### PR TITLE
Panel item settings and Clock Settings

### PR DESCRIPTION
**Pull request by RyanRiffle**
Hopefully this is at least up to your style. SettingsFragment has not been documented yet but it works.
The Clock PanelItem has been updated to allow changing the time settings.

### CODE REVIEW

**Comment by RyanRiffle** [comment]
Sorry I know the commits are a mess.

**Comment by andersevenrud** [comment]
Could you make the scheme file use double quotes ? I think it looks better that way

**Comment by RyanRiffle** [comment]
Not a problem.

**Comment by andersevenrud** [comment]
Also, could you please do:

``` if (typeof this._settings[key] !== 'undefined') ``` where these checks are done ? "=== undefined" will produce a lint error :)

**Comment by RyanRiffle** [comment]
I need to get a linter :smile:

**Comment by andersevenrud** [comment]
You can copy-paste into here: http://jshint.com/

Or even better set up a plugin for your editor :) I use https://www.bithound.io/github/andersevenrud/OS.js-v2/master for managing all linting and techdept. Pretty awesome stuff actually.

**Comment by andersevenrud** [comment]
Is this mergable now, or is more commits coming ?

**Comment by andersevenrud** [comment]
Will be doing a thurough test when I get off work and merge this :+1:

**Comment by andersevenrud** [comment]
Seems to be working like a charm

Nice job! :)

**Comment by andersevenrud** [comment]
I added docu to the settings-fragment

**Comment by andersevenrud** [comment]
@RyanRiffle In latest commit I have made abstraction for the settings stuff. So now everything is mostly done in `PanelItem`.

https://github.com/andersevenrud/OS.js-v2/blob/e229b96e056e73ab504465d6409d532fa47a5e53/src/packages/default/CoreWM/panelitems/clock.js

**Comment by RyanRiffle** [comment]
I wasn't doing anything in PanelItem itself just because I figured not all panel items would need settings but that works well too :smile:

**Comment by andersevenrud** [comment]
@RyanRiffle It has changed a little bit after a few more commits, but basically the same :)

**Comment by RyanRiffle** [comment]
Alright Ill just view the diff to get an update.

**Pull request merged**
