### PR TITLE
Added material theme

### PR DESCRIPTION
**Pull request by rontav**

### CODE REVIEW

**Comment by andersevenrud** [comment]
Did you look into the comments I made on gitter ? :)

**Comment by rontav** [comment]
I think so.

**Comment by TheMightyCraken** [comment]
Any news about if this will be added? Im a huge fan of Material :P

**Comment by andersevenrud** [comment]
@TheMightyCraken I will have a look later today. I forgot all about it :/

**Comment by andersevenrud** [comment]
Here are some comments: http://i.imgur.com/pyXV2Ki.jpg

Other than that, it looks good! :) It will look really good with per-application styles also.

I think I will modify the File Manager first to make it look like sort of what I initially envisioned (notice the two views sort of blending together as they do on the Android interfaces and such):

Screenshot

**Comment by andersevenrud** [comment]
I don't remember what comments I had earlier on this, but it seems that you've pretty much fixed it all.

**Comment by andersevenrud** [comment]
Allright! :+1:

**Comment by TheMightyCraken** [comment]
Awesome! is this live on the demo?

**Comment by andersevenrud** [comment]
@TheMightyCraken It is now (you might have to clear browser cache if you visited the demo before) :)

**Pull request merged**
