### PR TITLE
Docker Support

### PR DESCRIPTION
**Pull request by junland**
Logo

Alright, there we go. Automated build script and made some changes to the INSTALL.MD file to make it a lot shorter :)

### CODE REVIEW

**Comment by andersevenrud** [comment]
Allright! I will change the text in install *slightly* though

**Comment by junland** [comment]
Awesome! :)

**Comment by andersevenrud** [comment]
The result:

https://github.com/andersevenrud/OS.js-v2/blob/master/INSTALL.md

Basically, when I write installation documentation I make quite a few assumtions to avoid any clutter.

I, mean. If you have not heard about docker or know how to set it up, you'd probably want to use the official docs :)

**Comment by junland** [comment]
Looks good. :)
>I, mean. If you have not heard about docker or know how to set it up, you'd probably want to use the official docs :)

True lol

**Pull request merged**
