### PR TITLE
Added polish translation to pl_PL.js in src/client/javascript/locales/

### PR DESCRIPTION
**Pull request by marcinlimanski**
Added translation to the missing words, removed some extra spacing

### CODE REVIEW

**Comment by andersevenrud** [comment]
Hey :)

I cannot merge this because your branch is behind by 15 hours. You need to update your codebase before submitting patches.

**Comment by andersevenrud** [comment]
Hey :)

I managed to delete my last message... ops! It seems that your codebase is outdated and I cannot merge your patch. Please update your repo and try again.

**Comment by marcinlimanski** [comment]
No worries, will do that now

**Comment by marcinlimanski** [comment]
Should be good now

**Comment by andersevenrud** [comment]
> This branch has conflicts that must be resolved

I have to merge this manually -- hold on

**Comment by andersevenrud** [comment]
Oh, I see the problem here. Your repo was actually over 2 days old when you made that commit.

Someone else actually translated what you did after that:
- https://github.com/andersevenrud/OS.js-v2/commit/cc3adbe18719738a42362de797c620b90a932cfd
- https://github.com/andersevenrud/OS.js-v2/commit/467bbf899b3fb07b5737873264fbf68333db9ca7

So, sadly I have to close this request.

**Comment by marcinlimanski** [comment]
No worries, sorry about the inconvenience

**Comment by andersevenrud** [comment]
No problem! There's still probably some missing translations littered around though :)

**Comment by marcinlimanski** [comment]
Will have a look, thanks for this

**Pull request closed without merging**
