### PR TITLE
Add support for Docker.

### PR DESCRIPTION
**Pull request by junland**
Logo
Was finally able to create a working Docker image for OS.js (Took me several days of trail and error). I also added the working image to the Docker Hub repository and linked the project through there so that the project can also have some presence over in that space (https://registry.hub.docker.com/u/junland/osjs-dev/).

### CODE REVIEW

**Comment by andersevenrud** [comment]
Could you maybe make the INSTALL instructions a bit shorter? Take Vagrant as an example... I assume they already have knowledge on how to use it and just leave a link to the homepage. If there is any extra documentation that you would like to include, just make a *md* file in `doc/` and link to it in INSTALL :)

**Comment by andersevenrud** [comment]
Also, if you could revert the README.md file it would be awesome. I will be updating this in its entirety, so the layout will change.

**Comment by junland** [comment]
@andersevenrud How is that better? :)

**Comment by andersevenrud** [comment]
Hm. I was thinking more in the line of:


### Docker

A [docker.io](https://www.docker.com/) configuration is also included.

Just use [this configuration file](http://some-page) and you will be ready to go. For detailed instructions see the [separate documentation](http://)

**Comment by junland** [comment]
Actually I'll just whip up a bash script

**Comment by andersevenrud** [comment]
Even better :) Make sure to download new changes before making a new pull-request

**Comment by andersevenrud** [comment]
Or, actually, start a new pull-request so we avoid commit-message clutter :)

**Comment by junland** [comment]
Just about to type that out lol.

**Pull request closed without merging**
